[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "ipc"
version = "0.0.1"
description = "IPC library"
requires-python = ">=3.13"
dependencies = ["numpy >= 2.4"]
